# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'BaiduDemo' do

end

target 'BaiduDemoTests' do

end

target 'BaiduDemoUITests' do

end
 #百度地图SDK
pod 'BaiduMapKit'

